### ISSUE TITLE
What is the deal with the partial URLs?

### ISSUE THREAD

**Issue by Seahorses0** [newyokohama/improved-octo-waffle#1]
There's quite a few partial URLs like "details.php?id=#####", even under sections marked "done".
Archive.org doesn't seem to format their pages like that and if that is the last part of the URL for other site I don't know what it is. Are these coming in a future update or am I missing something?

**Comment by newyokohama** [comment]
> There's quite a few partial URLs like "details.php?id=#####", even under sections marked "done". Archive.org doesn't seem to format their pages like that and if that is the last part of the URL for other site I don't know what it is. Are these coming in a future update or am I missing something?

Thanks for the note, this is my fault, this document was internal to just myself for months, and then a very small group of people before it was finally shared out. Check for a disclaimer/header on the document in a few minutes. Thanks for reading.
